import { ClerkProvider} from '@clerk/nextjs';
import { Navigation } from "./components/navigation";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "BeachTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Modifying 'header' modifies the black border with the buttons
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <header className="text-white bg-black p-4 text-right"> 
              <Navigation />
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}